// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.metaTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metaTitle: prismicT.KeyTextField;
    /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.metaDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metaDescription: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = HeroSlice | ProjectCardSlice;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Página de projeto documents */
interface ProjectPageDocumentData {
    /**
     * Meta Title field in *Página de projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projectPage.metaTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metaTitle: prismicT.KeyTextField;
    /**
     * Nome do projeto field in *Página de projeto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projectPage.projectName
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    projectName: prismicT.RichTextField;
    /**
     * Banner field in *Página de projeto*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: projectPage.projectBanner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    projectBanner: prismicT.ImageField<never>;
    /**
     * Descrição do projeto field in *Página de projeto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projectPage.projectDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    projectDescription: prismicT.RichTextField;
    /**
     * Slice Zone field in *Página de projeto*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: projectPage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Página de projeto → Slice Zone*
 *
 */
type ProjectPageDocumentDataSlicesSlice = ProjectContentSlice;
/**
 * Página de projeto document from Prismic
 *
 * - **API ID**: `projectPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectPageDocumentData>, "projectPage", Lang>;
export type AllDocumentTypes = HomeDocument | ProjectPageDocument;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Logo field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.heroImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    heroImage: prismicT.ImageField<never>;
    /**
     * Título field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Descrição field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in ProjectCards → Primary
 *
 */
interface ProjectCardSliceDefaultPrimary {
    /**
     * Titulo da seção field in *ProjectCards → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: project_card.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in ProjectCards → Items
 *
 */
export interface ProjectCardSliceDefaultItem {
    /**
     * Project field in *ProjectCards → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project_card.items[].project
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    project: prismicT.RelationField<"projectPage">;
}
/**
 * Default variation for ProjectCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectCardSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectCardSliceDefaultPrimary>, Simplify<ProjectCardSliceDefaultItem>>;
/**
 * Slice variation for *ProjectCards*
 *
 */
type ProjectCardSliceVariation = ProjectCardSliceDefault;
/**
 * ProjectCards Shared Slice
 *
 * - **API ID**: `project_card`
 * - **Description**: `ProjectCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectCardSlice = prismicT.SharedSlice<"project_card", ProjectCardSliceVariation>;
/**
 * Item in ProjectContent → Items
 *
 */
export interface ProjectContentSliceDefaultItem {
    /**
     * Parágrafo field in *ProjectContent → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_content.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * Imagem field in *ProjectContent → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_content.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ProjectContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectContentSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ProjectContentSliceDefaultItem>>;
/**
 * Slice variation for *ProjectContent*
 *
 */
type ProjectContentSliceVariation = ProjectContentSliceDefault;
/**
 * ProjectContent Shared Slice
 *
 * - **API ID**: `project_content`
 * - **Description**: `ProjectContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectContentSlice = prismicT.SharedSlice<"project_content", ProjectContentSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, ProjectPageDocumentData, ProjectPageDocumentDataSlicesSlice, ProjectPageDocument, AllDocumentTypes, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice, ProjectCardSliceDefaultPrimary, ProjectCardSliceDefaultItem, ProjectCardSliceDefault, ProjectCardSliceVariation, ProjectCardSlice, ProjectContentSliceDefaultItem, ProjectContentSliceDefault, ProjectContentSliceVariation, ProjectContentSlice };
    }
}
