// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import ProjectCards from './ProjectCards';
import ProjectContent from './ProjectContent';

export {
	Hero,
	ProjectCards,
	ProjectContent,
};

export const components = {
	hero: Hero,
	project_card: ProjectCards,
	project_content: ProjectContent,
};
